# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainlink.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import erc20_pb2 as erc20__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63hainlink.proto\x12\x14messari.chainlink.v1\x1a\x0b\x65rc20.proto\"\xe0\x01\n\nAggregator\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12;\n\nbase_asset\x18\x03 \x01(\x0b\x32\x1c.messari.erc20.v1.ERC20TokenR\tbaseAsset\x12=\n\x0bquote_asset\x18\x04 \x01(\x0b\x32\x1c.messari.erc20.v1.ERC20TokenR\nquoteAsset\x12\x1a\n\x08\x64\x65\x63imals\x18\x05 \x01(\x04R\x08\x64\x65\x63imalsb\x06proto3')



_AGGREGATOR = DESCRIPTOR.message_types_by_name['Aggregator']
Aggregator = _reflection.GeneratedProtocolMessageType('Aggregator', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATOR,
  '__module__' : 'chainlink_pb2'
  # @@protoc_insertion_point(class_scope:messari.chainlink.v1.Aggregator)
  })
_sym_db.RegisterMessage(Aggregator)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGGREGATOR._serialized_start=55
  _AGGREGATOR._serialized_end=279
# @@protoc_insertion_point(module_scope)
