# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erc20.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rc20.proto\x12\x10messari.erc20.v1\"A\n\x0b\x45RC20Tokens\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32\x1c.messari.erc20.v1.ERC20TokenR\x05items\"\xb2\x01\n\nERC20Token\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n\x08\x64\x65\x63imals\x18\x04 \x01(\x04R\x08\x64\x65\x63imals\x12\x1d\n\ntx_created\x18\x05 \x01(\tR\ttxCreated\x12#\n\rblock_created\x18\x06 \x01(\x04R\x0c\x62lockCreated\"G\n\x0eTransferEvents\x12\x35\n\x05items\x18\x01 \x03(\x0b\x32\x1f.messari.erc20.v1.TransferEventR\x05items\"\xe6\x02\n\rTransferEvent\x12\x17\n\x07tx_hash\x18\x01 \x01(\tR\x06txHash\x12!\n\x0c\x62lock_number\x18\x02 \x01(\x04R\x0b\x62lockNumber\x12\x1c\n\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1b\n\tlog_index\x18\x04 \x01(\rR\x08logIndex\x12$\n\x0blog_ordinal\x18\x05 \x01(\x04H\x00R\nlogOrdinal\x88\x01\x01\x12#\n\rtoken_address\x18\x06 \x01(\tR\x0ctokenAddress\x12\x12\n\x04\x66rom\x18\x07 \x01(\tR\x04\x66rom\x12\x0e\n\x02to\x18\x08 \x01(\tR\x02to\x12\x16\n\x06\x61mount\x18\t \x01(\tR\x06\x61mount\x12G\n\x0f\x62\x61lance_changes\x18\n \x03(\x0b\x32\x1e.messari.erc20.v1.TokenBalanceR\x0e\x62\x61lanceChangesB\x0e\n\x0c_log_ordinal\"\x91\x02\n\x0cTokenBalance\x12$\n\x0blog_ordinal\x18\x01 \x01(\x04H\x00R\nlogOrdinal\x88\x01\x01\x12\x32\n\x05token\x18\x02 \x01(\x0b\x32\x1c.messari.erc20.v1.ERC20TokenR\x05token\x12\x18\n\x07\x61\x64\x64ress\x18\x03 \x01(\tR\x07\x61\x64\x64ress\x12$\n\x0bold_balance\x18\x04 \x01(\tH\x01R\noldBalance\x88\x01\x01\x12\x1f\n\x0bnew_balance\x18\x05 \x01(\tR\nnewBalance\x12\x1b\n\x06reason\x18\x06 \x01(\x05H\x02R\x06reason\x88\x01\x01\x42\x0e\n\x0c_log_ordinalB\x0e\n\x0c_old_balanceB\t\n\x07_reason\"E\n\rTokenBalances\x12\x34\n\x05items\x18\x01 \x01(\x0b\x32\x1e.messari.erc20.v1.TokenBalanceR\x05itemsb\x06proto3')



_ERC20TOKENS = DESCRIPTOR.message_types_by_name['ERC20Tokens']
_ERC20TOKEN = DESCRIPTOR.message_types_by_name['ERC20Token']
_TRANSFEREVENTS = DESCRIPTOR.message_types_by_name['TransferEvents']
_TRANSFEREVENT = DESCRIPTOR.message_types_by_name['TransferEvent']
_TOKENBALANCE = DESCRIPTOR.message_types_by_name['TokenBalance']
_TOKENBALANCES = DESCRIPTOR.message_types_by_name['TokenBalances']
ERC20Tokens = _reflection.GeneratedProtocolMessageType('ERC20Tokens', (_message.Message,), {
  'DESCRIPTOR' : _ERC20TOKENS,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.ERC20Tokens)
  })
_sym_db.RegisterMessage(ERC20Tokens)

ERC20Token = _reflection.GeneratedProtocolMessageType('ERC20Token', (_message.Message,), {
  'DESCRIPTOR' : _ERC20TOKEN,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.ERC20Token)
  })
_sym_db.RegisterMessage(ERC20Token)

TransferEvents = _reflection.GeneratedProtocolMessageType('TransferEvents', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFEREVENTS,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.TransferEvents)
  })
_sym_db.RegisterMessage(TransferEvents)

TransferEvent = _reflection.GeneratedProtocolMessageType('TransferEvent', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFEREVENT,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.TransferEvent)
  })
_sym_db.RegisterMessage(TransferEvent)

TokenBalance = _reflection.GeneratedProtocolMessageType('TokenBalance', (_message.Message,), {
  'DESCRIPTOR' : _TOKENBALANCE,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.TokenBalance)
  })
_sym_db.RegisterMessage(TokenBalance)

TokenBalances = _reflection.GeneratedProtocolMessageType('TokenBalances', (_message.Message,), {
  'DESCRIPTOR' : _TOKENBALANCES,
  '__module__' : 'erc20_pb2'
  # @@protoc_insertion_point(class_scope:messari.erc20.v1.TokenBalances)
  })
_sym_db.RegisterMessage(TokenBalances)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERC20TOKENS._serialized_start=33
  _ERC20TOKENS._serialized_end=98
  _ERC20TOKEN._serialized_start=101
  _ERC20TOKEN._serialized_end=279
  _TRANSFEREVENTS._serialized_start=281
  _TRANSFEREVENTS._serialized_end=352
  _TRANSFEREVENT._serialized_start=355
  _TRANSFEREVENT._serialized_end=713
  _TOKENBALANCE._serialized_start=716
  _TOKENBALANCE._serialized_end=989
  _TOKENBALANCES._serialized_start=991
  _TOKENBALANCES._serialized_end=1060
# @@protoc_insertion_point(module_scope)
