# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: erc721.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65rc721.proto\x12\reth.erc721.v1\"B\n\tTransfers\x12\x35\n\ttransfers\x18\x01 \x03(\x0b\x32\x17.eth.erc721.v1.TransferR\ttransfers\"~\n\x08Transfer\x12\x12\n\x04\x66rom\x18\x01 \x01(\x0cR\x04\x66rom\x12\x0e\n\x02to\x18\x02 \x01(\x0cR\x02to\x12\x19\n\x08token_id\x18\x03 \x01(\x04R\x07tokenId\x12\x19\n\x08trx_hash\x18\x04 \x01(\x0cR\x07trxHash\x12\x18\n\x07ordinal\x18\x05 \x01(\x04R\x07ordinalb\x06proto3')



_TRANSFERS = DESCRIPTOR.message_types_by_name['Transfers']
_TRANSFER = DESCRIPTOR.message_types_by_name['Transfer']
Transfers = _reflection.GeneratedProtocolMessageType('Transfers', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERS,
  '__module__' : 'erc721_pb2'
  # @@protoc_insertion_point(class_scope:eth.erc721.v1.Transfers)
  })
_sym_db.RegisterMessage(Transfers)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFER,
  '__module__' : 'erc721_pb2'
  # @@protoc_insertion_point(class_scope:eth.erc721.v1.Transfer)
  })
_sym_db.RegisterMessage(Transfer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFERS._serialized_start=31
  _TRANSFERS._serialized_end=97
  _TRANSFER._serialized_start=99
  _TRANSFER._serialized_end=225
# @@protoc_insertion_point(module_scope)
