# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eth_balance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65th_balance.proto\x12\x16messari.eth_balance.v1\"<\n\nEthBalance\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"G\n\x0b\x45thBalances\x12\x38\n\x05items\x18\x01 \x03(\x0b\x32\".messari.eth_balance.v1.EthBalanceR\x05itemsb\x06proto3')



_ETHBALANCE = DESCRIPTOR.message_types_by_name['EthBalance']
_ETHBALANCES = DESCRIPTOR.message_types_by_name['EthBalances']
EthBalance = _reflection.GeneratedProtocolMessageType('EthBalance', (_message.Message,), {
  'DESCRIPTOR' : _ETHBALANCE,
  '__module__' : 'eth_balance_pb2'
  # @@protoc_insertion_point(class_scope:messari.eth_balance.v1.EthBalance)
  })
_sym_db.RegisterMessage(EthBalance)

EthBalances = _reflection.GeneratedProtocolMessageType('EthBalances', (_message.Message,), {
  'DESCRIPTOR' : _ETHBALANCES,
  '__module__' : 'eth_balance_pb2'
  # @@protoc_insertion_point(class_scope:messari.eth_balance.v1.EthBalances)
  })
_sym_db.RegisterMessage(EthBalances)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ETHBALANCE._serialized_start=45
  _ETHBALANCE._serialized_end=105
  _ETHBALANCES._serialized_start=107
  _ETHBALANCES._serialized_end=178
# @@protoc_insertion_point(module_scope)
